### ISSUE TITLE
PATR

### ISSUE THREAD

**Issue by bheyde** [mivaecommerce/readytheme-suivant#15]
Plus/Minus buttons for Quantity don't work on PATR

**Comment by influxweb** [comment]
The PATR page should not be an issue as there should be no way to reach it through normal navigation or add to cart functions. If it is not currently that way, it will be once updated.

**Comment by bheyde** [comment]
We came across this issue on a store where they had 3 attributes, with but if you only selected 2, it would take you to PATR. 

We should either add the code to make the +/- buttons to work on that page or lets just remove them altogether from PATR

**Comment by influxweb** [comment]
If the frameworks isn't already reverted to the default, Miva, page layout, it will be in the next release. I know that Iron & Wool is using that layout.
